### ISSUE TITLE
KinectV2 Open Track build produces errors

### ISSUE THREAD

**Issue by Benadie911** [SaberShip/KinectV2OpenTrack#2]
@SaberShip , Hi, I hope you are well.  Not sure if you are still available to work on this small project but would appreciate if you could look at the attached error list and see if you can update the project to be able to be built using the latest version of Visual Studio?
I have tried to build it with VS 2022 as per this YouTube video (https://youtu.be/gycLrCXTTw8) but then get errors about .Net framework versions: it seems this project requires .Net 4.7.1 and VS 2022 installs .Net 4.8 already.  
I then uninstalled all about VS 2022 and installed VS 2017 as stated in the ReadMe, but still get the list of errors as per the attached.

I am not a developer so do not know how to go about fixing these errors.  If you tell me how to produce an official error list report in VS, I can produce it and send it to you, that is why I only attach a screenshot.

Regards and thanks for making the effort in producing this little program in the first place.
![KinectV2OpenTrack build errors](https://user-images.githubusercontent.com/123296945/213921079-82837661-83c9-495c-a962-7eed370a18e2.png)

**Comment by SaberShip** [comment]
It appears as though the Kinect SDK is not installed.  
As in the readme you can get the Microsoft Kinect SDK V2 [here](https://www.microsoft.com/en-us/download/details.aspx?id=44561)

Edit: You may need to reboot your system after installing this before it takes affect.

**Comment by Benadie911** [comment]
@SaberShip , thanks, That was the answer.  I had installed only the Kinect Runtime and not the complete SDK. Now it compiled no problem.
